import React from "react";

function InfoSection() {
  return (
    <>
      <div className="my-8 max-[599px]:h-[45vh] max-md:h-[40vh] md:h-[37vh] min-[900px]:h-[60vh] overflow-auto">
        <div className="pb-4">
          <h1 className="font-black text-2xl text-gray tracking-wide">What is provably fair?</h1>
          <p className="text-space-gray pt-2">
            Provably fair is a system utilized by RaidWin to provide players with the means to
            independently assess the integrity of each bet and confirm that no manipulation has
            occurred.
          </p>
          <p className="text-space-gray pt-2">
            The process involves the generation of random numbers, which determine the outcomes of
            bets. This generation is facilitated by combining a serverseed, a clientseed, and a
            nonce. Before a game begins, the serverseed is hashed and displayed to participants.
            This measure guarantees that the outcome of the bet remains unaltered throughout the
            game.
          </p>
        </div>
        <div className="pb-4">
          <h1 className="font-black text-2xl text-gray tracking-wide">Seeds</h1>
          <p className="text-space-gray pt-2">
            The system employs two distinct seeds along with a nonce to produce a random number
            within the range of 0 to 999999. This resultant number serves as the basis for
            calculating the final bet outcome. For instance, in the case of Doge vs Cheems , the
            number is subjected to a modulo of 3333.33 and then divided by 100 to yield the result.
            The exact calculations for all game types are provided in the code snippet at the bottom
            of this screen for all games.
          </p>
          <p className="text-space-gray pt-2">
            Serverseed: This seed is unique and generated randomly by the server.
          </p>
          <p className="text-space-gray pt-2">
            Clientseed: This seed is chosen by the client (yourself) and can be modified at any time
            by accessing your Provably Fair Settings.
          </p>
          <p className="text-space-gray pt-2">
            Serverseed: a unique and randomly generated seed, generated by the server.
            <p className="text-space-gray pt-2">
              Clientseed: This seed can be adjusted by the player(you) via the Provably Fair
              Settings at any time.
            </p>
          </p>
          <p className="text-space-gray pt-2">
            In order to verify the generated bet results, you must reveal the old serverseed and
            calculate the bet results. The previous serverseed is automatically revealed when you
            make a change to your clientseed at the Provably Fair Settings.
          </p>
          <p className="text-space-gray pt-2">
            To verify generated bet results, reveal the old serverseed and calculate the
            corresponding bet outcomes. When a change is made to the clientseed in the Provably Fair
            Settings, the previous serverseed is automatically revealed.
          </p>
          <p className="text-space-gray pt-2">
            As a precautionary measure, we recommend changing both seeds after a span of 90 days
            using the same seed. However, even after making these changes, it's still possible to
            verify previous bets.
          </p>
        </div>
        <div>
          <h1 className="font-black text-2xl text-gray tracking-wide">How to verify?</h1>
          <p className="text-space-gray pt-2">
            Verification can be carried out by accessing the Provably Fair Settings to modify the
            clientseed, enabling the review of past bets. Our Provably Fair verifier presents
            comprehensive details, aiding in comprehending the result generation process.
            Alternatively, you can utilize an external third-party verifier to compute the bet
            results.
          </p>
        </div>
      </div>
    </>
  );
}

export default InfoSection;
