import { InformationCircleIcon } from "@heroicons/react/outline";
import React from "react";
import { useEffect } from "react";
import { useState } from "react";
import { useSearchParams } from "react-router-dom";
import { server_seed } from "../../utils/ids";
import { baseUrl } from "../../utils/utils";
import { Tooltip } from "@mui/material";

function SettingsSection() {
  const [searchParams] = useSearchParams();

  let gameId = searchParams.get("gameId");

  // let { gameId } = useParams();
  const [serverSeedHashed, setServerSeedHashed] = useState("");

  const fetchServerSeedHashed = async () => {
    try {
      const resp = await fetch(`${baseUrl}/serverSeedHashed/${gameId}`);
      let serverSeedHashed = await resp.json();

      setServerSeedHashed(serverSeedHashed);
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    if (!gameId) return;
    fetchServerSeedHashed();
  }, [gameId]);

  return (
    <>
      <div className="my-8">
        <div className="text-2xl font-black tracking-wide text-gray">
          Settings
        </div>
        <div className="flex justify-center mt-5">
          <div className="w-full">
            <div className="mt-6 text-xl font-bold leading-6 tracking-wide text-center underline text-gray">
              Current Seeds
            </div>
            {/* <div className="mt-5 text-base font-semibold leading-6 tracking-wide text-gray">
              Server Seeds V3 (hashed)
            </div> */}
            <div className="w-full px-3 mt-5 mb-6 md:mb-0 ">
              <label className="flex items-center gap-2 mb-4 text-base font-semibold leading-6 tracking-wide text-gray">
                Server Seeds V3 (hashed)
                <Tooltip
                  title="A unique and randomly generated seed, generated by the server."
                  placement="right"
                >
                  <InformationCircleIcon className="h-5 w-5 text-opacity-[0.56] text-nouveau-main font-black" />
                </Tooltip>
              </label>
              <input
                className="block w-full bg-transparent p-4 border-[1.5px] border-nouveau-main focus:outline-none border-opacity-20 text-xs tracking-wider font-bold text-opacity-80 placeholder:tracking-wider placeholder:font-semibold rounded-lg text-space-gray placeholder:text-space-gray"
                type="text"
                value={serverSeedHashed.server_seed_hash}
              />
            </div>
            {/* <div className="mt-3 ">{serverSeedHashed.server_seed_hash}</div> */}

            {/* <div className="mt-4 text-base font-semibold leading-6 tracking-wide text-gray">
              Client Seed
            </div>
            <div className="mt-6 ">{server_seed.toString()}</div> */}
            <div className="w-full px-3 mt-5 mb-6 md:mb-0 ">
              <label className="flex items-center gap-2 mb-4 text-base font-semibold leading-6 tracking-wide text-gray">
                Client Seed
                <Tooltip
                  title="This seed is chosen by the client (yourself) and can be modified at any time by accessing your Provably Fair Settings."
                  placement="right"
                >
                  <InformationCircleIcon className="h-5 w-5 text-opacity-[0.56] text-nouveau-main font-black" />
                </Tooltip>
              </label>
              <input
                className="block w-full bg-transparent p-4 border-[1.5px] border-nouveau-main focus:outline-none border-opacity-20 text-xs tracking-wider font-bold text-opacity-80 placeholder:tracking-wider placeholder:font-semibold rounded-lg text-space-gray placeholder:text-space-gray"
                type="text"
                value={server_seed.toString()}
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default SettingsSection;
